config/routes.rb
HstTask::Application.routes.draw do

  root :to => 'collection#index'

  resources :collection

  match '/collection/sort' => 'collection#sort', :via => :post

end

app/models/collection.rb
class Collection < ActiveRecord::Base
  has_many :items
  accepts_nested_attributes_for :items
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :collection

def self.random_name
    name = ""
    name_length = rand(5..10)
    
    name = (1..name_length).map{ ('a'..'z').to_a[rand(26)] }.join
    
    return name 

  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/collection_controller.rb
class CollectionController < ApplicationController

  def index

    @collections = Collection.order(:position)
    

  end

  def new
    Collection.delete_all
    Item.delete_all
    
    collection1 = Collection.create(name: 'Collection 1', position: 1)

      item1 = Item.create(name: Item.random_name, position: 1, collection: collection1)
      item2 = Item.create(name: Item.random_name, position: 2, collection: collection1)
      item3 = Item.create(name: Item.random_name, position: 3, collection: collection1)
      item4 = Item.create(name: Item.random_name, position: 4, collection: collection1)
      item5 = Item.create(name: Item.random_name, position: 5, collection: collection1)

    
    collection2 = Collection.create(name: 'Collection 2', position: 2)

      item1 = Item.create(name: Item.random_name, position: 1, collection: collection2)
      item2 = Item.create(name: Item.random_name, position: 2, collection: collection2)
      item3 = Item.create(name: Item.random_name, position: 3, collection: collection2)
      item4 = Item.create(name: Item.random_name, position: 4, collection: collection2)
      item5 = Item.create(name: Item.random_name, position: 5, collection: collection2)

    collection3 = Collection.create(name: 'Collection 3', position: 3)   

      item1 = Item.create(name: Item.random_name, position: 1, collection: collection3)
      item2 = Item.create(name: Item.random_name, position: 2, collection: collection3)
      item3 = Item.create(name: Item.random_name, position: 3, collection: collection3)
      item4 = Item.create(name: Item.random_name, position: 4, collection: collection3)
      item5 = Item.create(name: Item.random_name, position: 5, collection: collection3)

  end

  def sort

    items = Item.order(:position)
    items.each do |item|
      if params['item'].include? item.id.to_s
        item.position = params['item'].index(item.id.to_s) + 1
        item.collection_id = params['collection']
        item.save
      end
    end
     render :nothing => true
  end

  
    
  


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collection_helper.rb
module CollectionHelper
end

app/views/collection/index.html.erb

<center>
	<h2>HST Task</h2>
<div class="outer_div">
<table>
	<tr>
		<% @collections.each do |collection| %>
		<th> <%= collection.name %> </th>
		<% end %>
	</tr>
	<tr>
		<% @collections.each do |collection| %>
		<td>
			<ul id="<%= collection.id %>" class="sort_list">
				<% collection.items.order(:position).each do |item| %>
					<li class="list_items" id="item_<%= item.id %>"><%= item.name %></li>
				<% end %>
			</ul>
		</td>
		<% end %>
	</tr>
</table>
</div>
<br>

<%= link_to 'Generate Items', new_collection_url %>
</center>

app/views/collection/new.html.erb
<%="success" %>
<br>
<%= link_to "View Table", root_url %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HstTask</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>